return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.lsp.ts-error-translator-nvim" },
  { import = "astrocommunity.recipes.auto-session-restore" },
  { import = "astrocommunity.recipes.cache-colorscheme" },
  { import = "astrocommunity.workflow.hardtime-nvim" },
  { import = "astrocommunity.note-taking.obsidian-nvim" },
  { import = "astrocommunity.media.cord-nvim" },
  { import = "astrocommunity.media.codesnap-nvim" },
  { import = "astrocommunity.git.blame-nvim" },
  { import = "astrocommunity.git.mini-diff" },
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.colorscheme.rose-pine" },
  { import = "astrocommunity.editing-support.conform-nvim" },
  { import = "astrocommunity.editing-support.nvim-treesitter-context" },
  { import = "astrocommunity.recipes.picker-lsp-mappings" },
  { import = "astrocommunity.recipes.picker-nvchad-theme" },
  { import = "astrocommunity.recipes.ai" },
}
